import {
  buildDesignPatch,
  getLLMRoleValidationIssues,
  buildMemoryPatch,
  buildToolsPatch,
  getReasoningCompilerProfile,
  getMemoryFieldErrors,
  getToolValidationIssues,
  isReasoningPatternSupported,
} from "@/features/blueprint/blueprint-adapter";

function buildMemoryValues(
  overrides: Partial<Parameters<typeof buildMemoryPatch>[0]> = {},
): Parameters<typeof buildMemoryPatch>[0] {
  return {
    agentScope: "El agente final solo conserva checkpoints aprobados.",
    configurationPreset: "session",
    goalDriftGuard: "Revalidar objetivo antes de cada accion con side effects",
    knowledgeChunkingPolicy: "",
    knowledgeCitationsPolicy: "No aplica porque no hay retrieval documental dedicado.",
    knowledgeConfidencePolicy: "Confiar solo en tools aprobadas y contexto capturado.",
    knowledgeContradictoryEvidenceBehavior: "Escalar cuando dos fuentes operacionales se contradigan.",
    knowledgeDeletionPolicy: "",
    knowledgeEmbeddingDimensions: "",
    knowledgeEmbeddingModel: "",
    knowledgeEmbeddingProvider: "",
    knowledgeEmbeddingVersion: "",
    knowledgeExcludeFiltersText: "",
    knowledgeExpirationPolicy: "",
    knowledgeFallbackBehavior: "",
    knowledgeIncludeFiltersText: "",
    knowledgeMetadataFieldsText: "",
    knowledgeMode: "none",
    knowledgeNoEvidenceBehavior: "Continuar con el workflow explicito si no existe evidencia adicional.",
    knowledgeNotes: "Caso sin RAG.",
    knowledgeParser: "",
    knowledgeRefreshFrequency: "",
    knowledgeRefreshTriggersText: "",
    knowledgeRetrievalFiltersText: "",
    knowledgeRerankingPolicy: "",
    knowledgeSearchMode: "",
    knowledgeSensitivityRulesText: "No empaquetar fuentes privadas.",
    knowledgeSources: [],
    knowledgeTopK: "",
    memoryCitationsPolicy: "Citar checkpoint y owner cuando exista memoria persistida.",
    memoryConfidencePolicy: "Reutilizar memoria solo si sigue vigente y aprobada.",
    memoryContradictoryEvidenceBehavior: "Escalar si un checkpoint contradice evidencia nueva.",
    memoryNoEvidenceBehavior: "Continuar con estado explicito si no hay memoria confiable.",
    memorySensitivityRulesText: "No persistir datos sensibles sin aprobacion.",
    memoryStrategy: " session_memory_with_checkpoints ",
    retentionPolicy: "Retener checkpoints 7 dias.",
    retrievalPolicy: "Recuperar contexto por prioridad y antiguedad",
    reviewTrigger: "Abrir revision cuando cambie el objetivo del usuario",
    storageLayersText: "session_state\ncheckpoint_summary\nuser_preferences",
    ttlPolicy: "Expirar cache en 24 horas.",
    workspaceScope: "El workspace conserva notas operativas.",
    writePolicy: "Persistir al cerrar cada checkpoint confirmado",
    ...overrides,
  };
}

describe("blueprint adapter", () => {
  it("builds a trimmed design patch from guided values", () => {
    expect(
      buildDesignPatch({
        architecture: " single_agent_with_skills ",
        llmBudgetPolicy: " Reservar reasoning para planner y evaluator. ",
        llmCircuitBreakerPolicy: " Abrir circuit breaker tras 3 fallos. ",
        llmContextPolicy: " Usar solo contratos aprobados. ",
        llmFallbackModel: " manual_review_gate ",
        llmFallbackPolicy: " Escalar a revision humana. ",
        llmFastModel: " gpt-5-mini ",
        llmLogRedactionPolicy: " Redactar secretos y datos sensibles. ",
        llmOutputValidationPolicy: " Validar contra schemas. ",
        llmProvider: " openai ",
        llmReasoningModel: " gpt-5.5 ",
        llmRoles: [
          {
            fallbackModel: "manual_review_gate",
            localId: "planner-1",
            maxTokens: "1800",
            model: "gpt-5.5",
            provider: "openai",
            reasoningEffort: "high",
            role: "planner",
            toolAvailabilityText: "",
          },
          {
            fallbackModel: "manual_review_gate",
            localId: "executor-1",
            maxTokens: "1600",
            model: "gpt-5-mini",
            provider: "openai",
            reasoningEffort: "medium",
            role: "executor",
            toolAvailabilityText: "",
          },
          {
            fallbackModel: "manual_review_gate",
            localId: "evaluator-1",
            maxTokens: "1800",
            model: "gpt-5.5",
            provider: "openai",
            reasoningEffort: "high",
            role: "evaluator",
            toolAvailabilityText: "",
          },
          {
            fallbackModel: "manual_review_gate",
            localId: "tool-use-1",
            maxTokens: "1200",
            model: "gpt-5-mini",
            provider: "openai",
            reasoningEffort: "medium",
            role: "tool_use",
            toolAvailabilityText: "consultar_crm\nactualizar_crm",
          },
        ],
        llmSamplingPolicy: " Temperatura baja y salidas estructuradas. ",
        memoryStrategy: " persistent_memory ",
        narrative: " Blueprint listo para pasar a tools. ",
        reasoningPattern: " ReAct ",
      }),
    ).toEqual({
      architecture: "single_agent_with_skills",
      llm_policy: {
        budget_policy: "Reservar reasoning para planner y evaluator.",
        circuit_breaker_policy: "Abrir circuit breaker tras 3 fallos.",
        context_policy: "Usar solo contratos aprobados.",
        fallback_model: "manual_review_gate",
        fallback_policy: "Escalar a revision humana.",
        fast_model: "gpt-5-mini",
        functions: [
          expect.objectContaining({ role: "planner" }),
          expect.objectContaining({ role: "executor" }),
          expect.objectContaining({ role: "evaluator" }),
          expect.objectContaining({
            role: "tool_use",
            tool_availability: ["consultar_crm", "actualizar_crm"],
          }),
        ],
        log_redaction_policy: "Redactar secretos y datos sensibles.",
        output_validation_policy: "Validar contra schemas.",
        provider: "openai",
        reasoning_model: "gpt-5.5",
        review_state: "needs-review",
        sampling_policy: "Temperatura baja y salidas estructuradas.",
      },
      memory_strategy: "persistent_memory",
      narrative: "Blueprint listo para pasar a tools.",
      reasoning_pattern: "ReAct",
    });
  });

  it("builds tool patches from the guided editor model", () => {
    expect(
      buildToolsPatch({
        guardrailsText: "No ejecutar side effects sin aprobacion.\nRegistrar trazabilidad por request.",
        tools: [
          {
            approvalReason: "Afecta datos del CRM",
            approvalPolicy: "local_admin_mandatory",
            archetype: "side_effect",
            auditRulesText: "Registrar request_id y version",
            authReference: "local_admin_session",
            compensationStrategy: "Revertir el cambio en CRM y registrar incidente",
            contractReviewState: "needs-review",
            endpointReference: "api://crm/leads",
            executionMode: "api_call",
            failureMode: "CRM no disponible",
            hasSideEffects: true,
            idempotencyStrategy: "lead_id + owner_id como clave idempotente",
            integrationKind: "api",
            inputsText: "lead_id\nowner_id",
            localId: "tool-1",
            name: " actualizar_crm ",
            owner: " local_admin ",
            outputsText: "estado\ntrace_id",
            permissionsText: "promote_blueprint\nupdate_crm",
            purpose: " Sincronizar datos comerciales ",
            rateLimitPolicy: "60 rpm por tenant",
            requiresApproval: true,
            retryStrategy: "Reintentar una vez con backoff",
            riskLevel: "high",
            scopesText: "write\ncrm",
            sensitiveDataText: "lead_profile",
            timeoutPolicy: "30 segundos con rollback",
            typedErrorsText: "crm_unavailable\nvalidation_error",
            validationsText: "Lead valido\nOwner valido",
          },
        ],
      }),
    ).toEqual({
      guardrails: [
        "No ejecutar side effects sin aprobacion.",
        "Registrar trazabilidad por request.",
      ],
      tools: [
        {
          approval_reason: "Afecta datos del CRM",
          approval_policy: "local_admin_mandatory",
          archetype: "side_effect",
          audit_rules: ["Registrar request_id y version"],
          auth_reference: "local_admin_session",
          compensation_strategy: "Revertir el cambio en CRM y registrar incidente",
          contract_review_state: "needs-review",
          endpoint_reference: "api://crm/leads",
          execution_mode: "api_call",
          failure_mode: "CRM no disponible",
          has_side_effects: true,
          idempotency_strategy: "lead_id + owner_id como clave idempotente",
          integration_kind: "api",
          inputs: ["lead_id", "owner_id"],
          name: "actualizar_crm",
          owner: "local_admin",
          outputs: ["estado", "trace_id"],
          permissions: ["promote_blueprint", "update_crm"],
          purpose: "Sincronizar datos comerciales",
          rate_limit_policy: "60 rpm por tenant",
          requires_approval: true,
          retry_strategy: "Reintentar una vez con backoff",
          risk_level: "high",
          scopes: ["write", "crm"],
          sensitive_data: ["lead_profile"],
          timeout_policy: "30 segundos con rollback",
          typed_errors: ["crm_unavailable", "validation_error"],
          validations: ["Lead valido", "Owner valido"],
        },
      ],
    });
  });

  it("flags duplicate and unsafe tool configurations before patching", () => {
    expect(
      getToolValidationIssues({
        guardrailsText: "",
        tools: [
          {
            approvalReason: "",
            approvalPolicy: "",
            archetype: "side_effect",
            auditRulesText: "",
            authReference: "",
            compensationStrategy: "",
            contractReviewState: "",
            endpointReference: "",
            executionMode: "api_call",
            failureMode: "",
            hasSideEffects: true,
            idempotencyStrategy: "",
            integrationKind: "",
            inputsText: "",
            localId: "tool-1",
            name: "consultar_crm",
            owner: "",
            outputsText: "",
            permissionsText: "",
            purpose: "",
            rateLimitPolicy: "",
            requiresApproval: false,
            retryStrategy: "",
            riskLevel: "high",
            scopesText: "",
            sensitiveDataText: "",
            timeoutPolicy: "",
            typedErrorsText: "",
            validationsText: "",
          },
          {
            approvalReason: "",
            approvalPolicy: "not_required",
            archetype: "read_only",
            auditRulesText: "Registrar request_id",
            authReference: "none",
            compensationStrategy: "No aplica",
            contractReviewState: "needs-review",
            endpointReference: "internal://crm/read",
            executionMode: "api_call",
            failureMode: "Sin respuesta",
            hasSideEffects: false,
            idempotencyStrategy: "Repetible sobre el mismo input",
            integrationKind: "api",
            inputsText: "lead_id",
            localId: "tool-2",
            name: " CONSULTAR_CRM ",
            owner: "builder",
            outputsText: "lead",
            permissionsText: "read_crm",
            purpose: "Consultar lead",
            rateLimitPolicy: "30 rpm",
            requiresApproval: false,
            retryStrategy: "Reintentar una vez",
            riskLevel: "low",
            scopesText: "read",
            sensitiveDataText: "",
            timeoutPolicy: "10 segundos",
            typedErrorsText: "crm_unavailable",
            validationsText: "Lead valido",
          },
        ],
      }),
    ).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          field: "owner",
          index: 0,
          message: "Declara el owner de la tool.",
        }),
        expect.objectContaining({
          field: "purpose",
          index: 0,
          message: "El proposito es obligatorio.",
        }),
        expect.objectContaining({
          field: "inputsText",
          index: 0,
          message: "Declara al menos un input.",
        }),
        expect.objectContaining({
          field: "requiresApproval",
          index: 0,
          message: "Toda tool con side effects debe exigir aprobacion.",
        }),
        expect.objectContaining({
          field: "typedErrorsText",
          index: 0,
          message: "Agrega al menos un error tipado.",
        }),
        expect.objectContaining({
          field: "name_duplicate",
          index: 1,
          message: "El nombre de la herramienta ya se uso en la fila 1.",
        }),
      ]),
    );
  });

  it("flags incomplete llm role policies before saving design", () => {
    expect(
      getLLMRoleValidationIssues({
        architecture: "single_agent_with_skills",
        llmBudgetPolicy: "Budget",
        llmCircuitBreakerPolicy: "Circuit breaker",
        llmContextPolicy: "Context",
        llmFallbackModel: "manual_review_gate",
        llmFallbackPolicy: "Fallback",
        llmFastModel: "gpt-5-mini",
        llmLogRedactionPolicy: "Redact logs",
        llmOutputValidationPolicy: "Validate output",
        llmProvider: "openai",
        llmReasoningModel: "gpt-5.5",
        llmRoles: [
          {
            fallbackModel: "",
            localId: "tool-use-1",
            maxTokens: "0",
            model: "",
            provider: "",
            reasoningEffort: "",
            role: "tool_use",
            toolAvailabilityText: "",
          },
        ],
        llmSamplingPolicy: "Low temperature",
        memoryStrategy: "persistent_memory",
        narrative: "Narrativa",
        reasoningPattern: "ReAct",
      }),
    ).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ field: "provider", index: 0 }),
        expect.objectContaining({ field: "model", index: 0 }),
        expect.objectContaining({ field: "maxTokens", index: 0 }),
        expect.objectContaining({ field: "fallbackModel", index: 0 }),
        expect.objectContaining({ field: "toolAvailabilityText", index: 0 }),
      ]),
    );
  });

  it("builds no-rag memory patches from the guided editor model", () => {
    expect(buildMemoryPatch(buildMemoryValues())).toEqual({
      knowledge_profile: {
        embedding_policy: {
          dimensions: 0,
          model: "",
          provider: "",
          version: "",
        },
        grounding_policy: {
          citations_policy: "No aplica porque no hay retrieval documental dedicado.",
          confidence_policy: "Confiar solo en tools aprobadas y contexto capturado.",
          contradictory_evidence_behavior: "Escalar cuando dos fuentes operacionales se contradigan.",
          no_evidence_behavior: "Continuar con el workflow explicito si no existe evidencia adicional.",
        },
        ingestion_policy: {
          chunking_policy: "",
          exclude_filters: [],
          include_filters: [],
          metadata_fields: [],
          parser: "",
        },
        mode: "none",
        notes: "Caso sin RAG.",
        refresh_policy: {
          deletion_policy: "",
          expiration_policy: "",
          frequency: "",
          triggers: [],
        },
        retrieval_policy: {
          fallback_behavior: "",
          filters: [],
          reranking_policy: "",
          search_mode: "",
          top_k: 0,
        },
        sensitivity_rules: ["No empaquetar fuentes privadas."],
        sources: [],
      },
      memory_profile: {
        agent_scope: "El agente final solo conserva checkpoints aprobados.",
        goal_drift_guard: "Revalidar objetivo antes de cada accion con side effects",
        grounding_policy: {
          citations_policy: "Citar checkpoint y owner cuando exista memoria persistida.",
          confidence_policy: "Reutilizar memoria solo si sigue vigente y aprobada.",
          contradictory_evidence_behavior: "Escalar si un checkpoint contradice evidencia nueva.",
          no_evidence_behavior: "Continuar con estado explicito si no hay memoria confiable.",
        },
        retention_policy: "Retener checkpoints 7 dias.",
        retrieval_policy: "Recuperar contexto por prioridad y antiguedad",
        review_trigger: "Abrir revision cuando cambie el objetivo del usuario",
        sensitivity_rules: ["No persistir datos sensibles sin aprobacion."],
        storage_layers: ["session_state", "checkpoint_summary", "user_preferences"],
        strategy: "session_memory_with_checkpoints",
        ttl_policy: "Expirar cache en 24 horas.",
        workspace_scope: "El workspace conserva notas operativas.",
        write_policy: "Persistir al cerrar cada checkpoint confirmado",
      },
      memory_strategy: "session_memory_with_checkpoints",
    });
  });

  it("validates required memory policies before saving", () => {
    expect(
      getMemoryFieldErrors(
        buildMemoryValues({
          agentScope: "",
          goalDriftGuard: "",
          memoryCitationsPolicy: "",
          memoryConfidencePolicy: "",
          memoryNoEvidenceBehavior: "",
          memorySensitivityRulesText: "",
          memoryStrategy: "",
          retentionPolicy: "",
          retrievalPolicy: "",
          reviewTrigger: "",
          storageLayersText: "",
          ttlPolicy: "",
          workspaceScope: "",
          writePolicy: "",
        }),
      ),
    ).toEqual({
      agentScope: "Separa la memoria del agente final.",
      goalDriftGuard: "Define como se protege el objetivo.",
      memoryCitationsPolicy: "Define como se citan los checkpoints o artefactos.",
      memoryConfidencePolicy: "Define cuando confiar en memoria previa.",
      memoryNoEvidenceBehavior: "Define el fallback sin evidencia de memoria.",
      memorySensitivityRulesText: "Declara reglas de sensibilidad para memoria.",
      memoryStrategy: "Selecciona una estrategia de memoria.",
      retentionPolicy: "Define la politica de retencion.",
      retrievalPolicy: "Define la politica de recuperacion.",
      reviewTrigger: "Define cuando debe entrar en revision.",
      storageLayersText: "Declara al menos una capa de memoria.",
      ttlPolicy: "Define la politica TTL.",
      workspaceScope: "Separa la memoria del workspace.",
      writePolicy: "Define la politica de escritura.",
    });
  });

  it("validates rag-specific sources and retrieval policies", () => {
    expect(
      getMemoryFieldErrors(
        buildMemoryValues({
          configurationPreset: "rag",
          knowledgeMode: "rag",
          knowledgeCitationsPolicy: "",
          knowledgeChunkingPolicy: "",
          knowledgeConfidencePolicy: "",
          knowledgeEmbeddingDimensions: "0",
          knowledgeEmbeddingModel: "",
          knowledgeEmbeddingProvider: "",
          knowledgeEmbeddingVersion: "",
          knowledgeExpirationPolicy: "",
          knowledgeFallbackBehavior: "",
          knowledgeNoEvidenceBehavior: "",
          knowledgeParser: "",
          knowledgeRefreshFrequency: "",
          knowledgeRefreshTriggersText: "",
          knowledgeSearchMode: "",
          knowledgeSensitivityRulesText: "",
          knowledgeSources: [
            {
              description: "",
              license: "",
              localId: "source-1",
              owner: "",
              sensitivity: "",
              sourceType: "",
              sourceVersion: "",
              title: "",
              uri: "",
            },
          ],
          knowledgeTopK: "0",
        }),
      ),
    ).toEqual(
      expect.objectContaining({
        knowledgeChunkingPolicy: "Define la politica de chunking.",
        knowledgeCitationsPolicy: "Define la politica de citas para retrieval.",
        knowledgeConfidencePolicy: "Define la politica de confianza para retrieval.",
        knowledgeEmbeddingDimensions: "Define dimensions validas para embeddings.",
        knowledgeEmbeddingModel: "Define el modelo de embeddings.",
        knowledgeEmbeddingProvider: "Define el provider de embeddings.",
        knowledgeEmbeddingVersion: "Declara la version de embeddings.",
        knowledgeExpirationPolicy: "Define la expiracion del knowledge.",
        knowledgeFallbackBehavior: "Define el fallback cuando retrieval no encuentra evidencia.",
        knowledgeNoEvidenceBehavior: "Define el comportamiento sin evidencia.",
        knowledgeParser: "Define el parser de ingestion.",
        knowledgeRefreshFrequency: "Define la frecuencia de refresh.",
        knowledgeRefreshTriggersText: "Declara al menos un trigger de refresh.",
        knowledgeSearchMode: "Define el modo de busqueda.",
        knowledgeSensitivityRulesText: "Declara reglas sensibles para knowledge.",
        knowledgeSources: "Cada fuente debe incluir titulo, tipo, URI, owner, sensibilidad y version.",
        knowledgeTopK: "Define un top-k valido para retrieval.",
      }),
    );
  });

  it("exposes the local S4 compiler support matrix for reasoning patterns", () => {
    expect(isReasoningPatternSupported("Plan-and-Execute")).toBe(true);
    expect(isReasoningPatternSupported("ReAct")).toBe(true);
    expect(isReasoningPatternSupported("HTN")).toBe(false);

    expect(getReasoningCompilerProfile("ToT")).toEqual(
      expect.objectContaining({
        control: "Alto",
        latency: "Alta",
        status: "planned",
      }),
    );
  });
});
